from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ee412de43cb6'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint('uq_contact_email', ['email'])  # Corrected this line
        batch_op.drop_column('emai')  # Fixed the typo here, change 'emai' to 'email'

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emai', sa.VARCHAR(length=120), nullable=False))  # Add the 'emai' column back in downgrade
        batch_op.drop_constraint('uq_contact_email', type_='unique')  # Drop the unique constraint by its name
        batch_op.drop_column('email')

    # ### end Alembic commands ###
